### ISSUE TITLE
Deck comparison

### ISSUE THREAD

**Issue by malens** [moxfield/moxfield-public#2]
Create a deck comparison/diff tool.

**Comment by ArtSabintsev** [comment]
On top of that, make sure you can:

- See the differences between each deck
- Export either diff to [TCGPlayer Mass Entry ](https://store.tcgplayer.com/massentry)
- Export the diff in other formats (txt, csv, mtgo, etc.)

**Comment by Arsteel** [comment]
Currently doesn't show difference in card quantity, which is essential for non-singleton formats.
