### ISSUE TITLE
Category search functionality

### ISSUE THREAD

**Issue by pongo-pygmaeu5** [moxfield/moxfield-public#23]
Would be a nice QoL improvement to implement a feature allowing for easy searching of commonly used categories of cards. This would make building singleton decks less tedious and, depending on how rich the feature gets, could even help with brewing decks in all formats. 

e.g. if a user searches for "fetchland" or "fetchlands" then have all 10 of the true fetchlands appear as search results. Another example: "shockland" to have all 10 Ravnica shocklands show up.

A large number of categories like this can be brainstormed.

-"Shocklands" or "shocks"
-"Bouncelands" or "karoos"
-"ABUR" or "Duals"
-"Fetchlands" or "fetches"
-"Tutors"
-"Burn"
-"Counters" 
-"Wheels" 

etc.

**Comment by tobsecret** [comment]
Isn't this already implemented in the scryfall search?
https://scryfall.com/docs/syntax#shortcuts

You can type for example `is:karoo` - now not all of the ones on your list are implemented but the concept itself is via scryfall.
