### ISSUE TITLE
User Inventory

### ISSUE THREAD

**Issue by ArtSabintsev** [moxfield/moxfield-public#3]
As a user, it would be great if I could have a page denoting my current paper (or digital MTGO) inventory of card. This should allow for multiple versions of the same card, but different printings (and foiled versions of the same printing) to be denoted as separate entry.

Then, in the deck builder, it would be great if I could choose a card from my inventory (as an added options on top of switching printings)

**Comment by KohlJary** [comment]
Adding onto this, it would be cool if I could see how many copies of a card I have that aren't in a deck, as well as what decks any copies I own are currently in, to plan out buying cards and potentially disassembling decks.
