### ISSUE TITLE
adding cards directly to sideboard / considering

### ISSUE THREAD

**Issue by Ruberto** [moxfield/moxfield-public#31]
Just how you prefix a card with a number when adding it to the list, could you have a way to prefix the card so that it's loaded directly into the `sideboard` / `considering` sections of the decklist? 

My current approach is to add the card then click on it and move it to the section. It's more a useability feature. 

consider adding a tooltip to appear over/under the search when a mouse hovers for a specific time to show the different ways of loading cards through the text field.

**Comment by harryfino** [comment]
You can already use `considering:` and `sideboard:` as a way to add directly to these boards. I will be working on a UI for this at some point.
