### ISSUE TITLE
Add card to deck from compare view

### ISSUE THREAD

**Issue by BartDuwez** [moxfield/moxfield-public#40]
Minor feature request. I made a "deck" called Inventory. When I compare Inventory to another one of my decks I can see a list off images. When I click an image I go to the detail view. 

Now I'm looking for cards in my real life inventory that are unique to a deck, they are not added to the digital inventory yet.

I couldn't find a way to add one of the cards, unique to a deck but in my real inventory, to my digital inventory.

It would be handy if that would be possible.

**Comment by harryfino** [comment]
This feature is available now.
